### ISSUE TITLE
Simulations in Figure 1

### ISSUE THREAD

**Issue by simkovic** [tyarkoni/generalizability#1]
https://github.com/tyarkoni/generalizability/blob/40d405bb90af2424ac531c4cb1d04e3e9eaef7a7/notebooks/Figure-1.ipynb#L64

The above-cited line is not consistent with Model (2) description in manuscript (p.5). Probably, what was intended was: 
`mu = (b_intercept + b_condition * df['condition'] + u_intercept[df['subject']]*(1-df['condition']) + 
              u_condition[df['subject']] * df['condition'])`

Apart from that, the choice of Model (1) and Model (2) is dubious. It makes the comparison convoluted and it is not clear whether the estimates are affected by the fact that M1 and M2 differ in terms of hierarchical structure or rather that the estimates are affected by other aspects that distinguish the two models. A direct comparison can be obtained either by modifying M1 to 

`        b_intercept = pm.Normal('intercept', mu=0, sd=1)
        b_condition = pm.Normal('condition', mu=0, sd=1)
        u_intercept_sigma = pm.HalfNormal('subject_intercept_sigma', 2)
        u_intercept = pm.Normal('subject_intercept', mu=0, sd=u_intercept_sigma)
        u_condition_sigma = pm.HalfNormal('subject_condition_sigma', 2)
        u_condition = pm.Normal('subject_condition', mu=0, sd=u_condition_sigma)
        mu = (b_intercept + b_condition * df['condition'] + u_intercept[df['subject']]*(1-df['condition']) + 
              u_condition[df['subject']] * df['condition'])
        sigma = pm.HalfNormal('sigma', 2)
        y_hat = pm.Normal('y_hat', mu, sigma, observed=df['y'])`

or by modifying M2 to 
`       
        b_intercept_mu = pm.Normal('intercept', mu=0, sd=1)
        b_intercept_sigma = pm.HalfNormal('subject_intercept_sigma', 2)
        b_intercept = pm.Normal('intercept', mu=b_intercept_mu, sd=b_intercept_sigma,shape=n_subs)
        b_condition = pm.Normal('condition', mu=0, sd=1)
        mu = b_intercept + b_condition * df['condition']
        sigma = pm.HalfNormal('sigma', 2)
        y_hat = pm.Normal('y_hat', mu, sigma, observed=df['y'])`

My simulations suggest that the difference in the variance of estimates  between the two models vanishes, which undermines the conclusions made in the report.

**Comment by tyarkoni** [comment]
I think the notebook is correct—it's Eq. (2) in the paper that's wrong (and will be fixed when I upload a revised version).

I'm not sure what you mean by the choice being dubious. The point here is to compare fixed-effects and random-effects conceptualizations of the data-generating process. Your proposed modifications don't capture that. E.g., your proposed M2 modification drops random subject slopes. It seems pretty obvious that omitting thr varying slopes is going to produce a common slope estimate with variance much closer to the fixed-effect model, but that's precisely the point! The reason you add the varying slopes is because you intend to generalize to a population of people who you believe differ in their Stroop effects. If you *don't* believe that, then you would never have reason to fit such a model.

**Comment by simkovic** [comment]
1. You forgot to comment about my proposed modification to M1. It compares fixed-effects and random-effects conceptualizations of the data-generating process. That's your point, isn't it?

2. > It seems pretty obvious that omitting thr varying slopes is going to produce a common slope estimate with variance much closer to the fixed-effect model

So Your proposition is that there is no benefit of using random-intercepts over fixed-intercepts model (fixed slopes both)? If yes, You should make this clear in the report that the necessary aspect is whether the slopes are random or not, and that random intercepts do not affect the estimates. If no, then the results of my proposed modification to M2 are relevant to Your proposition and should be checked as they potentially show that your alternative proposition is incorrect.

3. If You want varying slopes it's straightforward to modify my proposal to M2 further to accommodate Your needs:

``b_intercept_mu = pm.Normal('intercept_mu', mu=0, sd=1) 
b_intercept_sigma = pm.HalfNormal('subject_intercept_sigma', 2) 
b_intercept = pm.Normal('intercept', mu=b_intercept_mu, sd=b_intercept_sigma,shape=n_subs) 
b_condition_mu = pm.Normal('condition', mu=0, sd=1) 
b_condition_sigma = pm.HalfNormal('subject_slope_sigma', 2) 
b_condition = pm.Normal('slope', mu=b_condition_mu, sd=b_condition_sigma,shape=n_subs) 
mu = b_intercept[df['subject']] + b_condition[df['subject']] * df['condition'] 
sigma = pm.HalfNormal('sigma', 2) 
y_hat = pm.Normal('y_hat', mu, sigma, observed=df['y'])``

So again, we have fixed-effects and random-effects conceptualizations of the data-generating process.

**Comment by tyarkoni** [comment]
> You forgot to comment about my proposed modification to M1. It compares fixed-effects and random-effects conceptualizations of the data-generating process. That's your point, isn't it?

Your M1 modification is just a re-parameterization of my M2 with separate slopes for each condition instead of intercept + slope. It gives the same result because it's basically the same model.

> So Your proposition is that there is no benefit of using random-intercepts over fixed-intercepts model (fixed slopes both)?

No. The claim is that given the experimental design and generalization intention, it would be very strange to fit a model without varying slopes and varying intercepts. That would imply that one thinks people all have the same mean reaction time and/or Stroop effect, which is ludicrous on its face. If your goal is to generalize to new subjects, M1 is an inappropriate model. M2, while still not in any sense "correct", remedies the most obvious problem with M1, namely, it's failure to model subject sampling variability. If you want to argue that we live in a world where people all share the same mean reaction time, but show different Stroop effects, I'm listening. But it's immaterial to the point in the paper which of the variance components most impacts the fixed effect estimates (though it will generally be the slopes, given that the fixed slope is the parameter of interest). The point is that M2 is the model that passes a basic sanity test given the generalization intention, whereas M1 doesn't.

> If You want varying slopes it's straightforward to modify my proposal to M2 further to accommodate Your needs:

Not sure I see the point of this. M2 already had varying slopes. What you have here is essentially the same model as M2, except with a constraint that yokes the distribution means to the mu parameters. This provides no conceptual benefit that I can see, and the dependence is likely to make the sampler's job more difficult than the existing parameterization (though, in the very long run, I think they should produce the same estimates).

**Comment by simkovic** [comment]
Perhaps the proposed modifications result in identical models, I don't think this is the case with M1 modification, which differs in terms of variance of prior distribution from the original M1. Well, whom should we ask to find out - whom should we ask to derive the posterior pdf for the modified model, whom should we ask to run the simulations? Should we perhaps ask the principal investigator?

I find it hard to continue this exchange as I don't get the impression that You are interested in finding out what is the reason why the uncertainty of grand average estimates of the random slopes model differs from the estimates of the random offsets model and from the estimates of the completely-pooled model, with the latter two being identical.
